spring.application.name=baseapi

#spring.datasource.url=jdbc:mysql://mysql_9906:9906/baseapi_db
spring.datasource.url=jdbc:mysql://localhost:3306/baseapi_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

logging.level.org.springframework.validation=DEBUG

spring.cloud.aws.region.static=us-east-1

jwt.secret=P50012ymQHPw471!
